name: Terraform plan / apply

on:
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - dev
        - stage
        - prod
        default: dev
  

jobs:

  build:
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
    
    - name: Terraform Format
      run: terraform fmt
           terraform fmt -check

    - name: Terraform plan 
      run: |
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        terraform init
        terraform workspace select ${{ github.event.inputs.environment }}
        terraform plan -var="machine_size="Standard_B1s"" -var-file vars.${{ github.event.inputs.environment }}.tfvars -out ${{ github.event.inputs.environment }}.plan
    - name: Test with Checkov
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
          directory: .
          framework: terraform
    - name: Terraform apply
      run: |
        terraform workspace select ${{ github.event.inputs.environment }}
        terraform apply --auto-approve "${{ github.event.inputs.environment }}.plan"

    - name: Terraform output
      run: |
        mkdir -p output
        terraform output -json > output/${{ github.run_id }}_apply.json

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: terraform_output
        path: |
          output/
